version: "3.9"

services:
  db:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: loadsg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - loadsg-network

    restart: unless-stopped

networks:
  loadsg-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.1.0/24

volumes:
  postgres_data:
